### ISSUE TITLE
miss loco_cluster_labels.pk

### ISSUE THREAD

**Issue by wanzijing12** [lrcfmd/LiIonML#3]
File "/root/PycharmProjects/pythonProject/LiIonML-master/dp.py", line 273, in <module>
    lab = pk.load(open(f"data/loco_cluster_labels.pk", "rb"))

**Comment by SurgeArrester** [comment]
Hi @wanzijing12, this file is purposely not included as the embedding that is created with UMAP will vary depending on the initial embedding which means that the loco cluster labels will be slightly different on each run. You will have to generate these cluster labels in the notebook
