### ISSUE TITLE
df = pd.read_csv("data/ml_dataset.csv")，all_comps  = pk.load(open("data/all_comps.pk", "rb"))where is it?(ml_dataset.csv)

### ISSUE THREAD

**Issue by Yong-Q** [lrcfmd/LiIonML#6]

**Comment by SurgeArrester** [comment]
Hi Yong, thanks for reporting this. The licence for using the ICSD dataset makes it very clear that any information from this dataset cannot be shared with others without express permission from Fitz-Karlsruhe so we did not include it. We have had permission to share limited subsets of the compositions as part of a separate project, so I will ask if we can be given permission to distribute these compositions as part of this project, but that may not be granted. 

If you wish to replicate this study immediately whilst I'm waiting for a reply, then you should be able to get similar results using a freely available set of compositions such as the materials project

**Comment by Yong-Q** [comment]
I would like to know what the contents of these files look like so that I can reproduce them. Maybe you can give some examples, such as "all_comps.pk" and so on，thanks!

**Comment by SurgeArrester** [comment]
This is just a python list of strings of each composition saved as a pickle

![image](https://github.com/lrcfmd/LiIonML/assets/7188805/9a83aa62-94bb-4f71-ab41-663de3e28c21)
