### ISSUE TITLE
Could you please provide "loco_cluster_labels.pk"? It is very important to me, thank you!

### ISSUE THREAD

**Issue by kikaaaaww** [lrcfmd/LiIonML#7]
If possible, can you provide "loco_cluster_labels.pk"?

**Comment by SurgeArrester** [comment]
Hi @kikaaaaww , I've uploaded that file to LiIonML/data, although this data should be relatively easy to generate and validate from the notebooks 🙂 let me know if you run into any issues

**Comment by kikaaaaww** [comment]
Thank you for your answer. Could you please provide the "all_comps.pk" file and the "ml_dataset.csv" file?

**Comment by SurgeArrester** [comment]
Hi @kikaaaaww, these are licensed by the university of liverpool and I'm not permitted to share them without the license header that is given at the website URL as reported in the manuscript. You will need to download this csv from https://pcwww.liv.ac.uk/~msd30/lmds/LiIonDatabase.html, remove the header, then follow the steps in the provided notebooks to generate this data yourself

**Comment by kikaaaaww** [comment]
Thank you very much for your answer! I'll try it.

**Comment by SurgeArrester** [comment]
Best of luck!

**Comment by kikaaaaww** [comment]
Hi, I have one more question. Could you please tell me how to write the numbers in the "data/loco_cluster_labels.pk" file in the order and according to which attribute?
